name: Build documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'Writerside/in'
  ARTIFACT: 'webHelpIN2-all.zip'
  DOCKER_VERSION: '241.15989'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 7
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d dir

      - name: Naver Search Advisor 1
        run: cd dir && touch naver92825af1abbb23b37af4d3588f7f08e6.html && echo "naver-site-verification:_SPACE_naver92825af1abbb23b37af4d3588f7f08e6.html" >> naver92825af1abbb23b37af4d3588f7f08e6.html

      - name: Naver Search Advisor 2
        run: cd dir && sed -i -e 's/_SPACE_/ /g' naver92825af1abbb23b37af4d3588f7f08e6.html

      - name: Create robots.txt 1
        run: cd dir && touch robots.txt && echo "User-agent:_SPACE_*" >> robots.txt && echo "Allow:_SPACE_/" >> robots.txt && echo "Sitemap:_SPACE_https://rundevelrun.6developer.com/sitemap.xml" >> robots.txt

      - name: Create robots.txt 2
        run: cd dir && sed -i -e 's/_SPACE_/ /g' robots.txt

      - name: Adsense
        run: cd dir && sed -i -e 's#<p id="adsense-bar" class="article__p h2-related">-</p>#<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2327476184552798" crossorigin="anonymous"></script><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2327476184552798" data-ad-slot="1572389002" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>#g' robots.txt

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
